### ISSUE TITLE
Ag grid theme column menu is not scrollable depending on bundler

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3581]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

v1.4.1

### Description

Column menu (click triple dot menu on column header, third column tab) is not scrollable, columns tool panel columns can not be scrolled to the bottom

| Bundler | Dev | Prod | 
| --- | --- | --- |
| [StackBlitz](https://stackblitz.com/edit/salt-ag-grid-theme-mkzbkc?file=App.jsx) | ok | n/a |
| [Salt site](https://www.saltdesignsystem.com/salt/components/ag-grid-theme/examples) | - | bug |
| CRA v5 | bug | bug |
| Vite v5 | ok | ok |

The problem is due to CSS minification, where flex `0px` is being minified away.

```
/* ag-grid.css */
.ag-column-select-list {
  -webkit-box-flex: 1;
          flex: 1 1 0px;
  overflow: hidden;
}
```

Minified to:

```css
.ag-column-select-list {
    flex: 1 1;
    overflow: hidden;
}
```

### Potential fix

Remove below 2 sets of CSS. Additional vertical spacing needs to be adjusted before the search input and after the list.

```css
.ag-theme-salt-high-compact-light .ag-column-select-list {
    overflow: initial;
}
```

```css
.ag-theme-salt-high-compact-light .ag-menu-column-select-wrapper {
    height: 100%;
}
```

### Operating system

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.
